### ISSUE TITLE
Sorting by date when plotting a series of "daily metrics"

### ISSUE THREAD

**Issue by mrdavidlaing** [0w0miki/logseq-plugin-query-chart#4]
Thank for your creating a great plugin!

I've been trying to follow the ["OKR Tracker" example](https://github.com/0w0miki/logseq-plugin-query-chart#example-%E7%A4%BA%E4%BE%8B); but just cannot for the life of me figure out how to write a query so the results are returned in date order.

My setup is as follows.

On each daily journal page I have an "exersize" TODO with a `pace-best-mile:: ` block property:

![image](https://github.com/0w0miki/logseq-plugin-query-chart/assets/227505/1f65d596-711c-42c8-820d-1557a7406a56)

I want to plot a chart to show the trend of how the `pace-best-mile:: ` metric is changing day by day. (I'm trying to get fitter :) )

This is what I have sofar - it **almost** works except that the days on the X axis aren't in date order :( 

![image](https://github.com/0w0miki/logseq-plugin-query-chart/assets/227505/b3e33661-f0bb-4a05-b3ac-c2c075fbba15)

This makes sense because the results of the query I'm using aren't in date order either.

Here is the query I'm using:

```clojure
#+BEGIN_QUERY
{
  :query [:find ?date ?result
          :in $ ?start ?today
          :where
		; blocks from Journal pages between ?start and ?today
		[?b :block/page ?journal]
		[?journal :block/name ?date]
		[?journal :block/journal-day ?d]
			[(>= ?d ?start)]
			[(< ?d :today)]
		; value of pace-best-mile:: properties
		[?b :block/properties ?block_props]
		[(get ?block_props :pace-best-mile nil) ?result]
  ]
  :inputs [:30d-before :today]
}
#+END_QUERY
```

How can I order the X axis values in date order?

Thanks!

**Comment by 0w0miki** [comment]
Hi, please try the new version v0.5.5. The result of advanced query is sorted by default.

**Comment by mrdavidlaing** [comment]
Awesome!  That works for me.

🙇🏼 

<img width="624" alt="image" src="https://github.com/0w0miki/logseq-plugin-query-chart/assets/227505/3ae20a14-3da3-4523-8643-508a8de343f5">
