### ISSUE TITLE
Query inputs like `:7d-before` result in "Query Failed"  

### ISSUE THREAD

**Issue by mrdavidlaing** [0w0miki/logseq-plugin-query-chart#5]
## Problem
The `feat: support new advanced query date input format` feature implemented in  edb5610b0e9cc41c40e04ab305a877c6e60a9f9d seems to have broken support for query `:input` formats like

```
 :inputs [:7d-before :today]
```

![image](https://github.com/0w0miki/logseq-plugin-query-chart/assets/227505/ae2a31a2-7581-4c61-867e-a43419b8d8b5)

The following message is logged to the Dev console:
![image](https://github.com/0w0miki/logseq-plugin-query-chart/assets/227505/748b116a-6589-426c-9fcd-b59de7f961c1)

Even though Logseq considers the query syntax to be valid and does render out the data
![image](https://github.com/0w0miki/logseq-plugin-query-chart/assets/227505/52ff118d-d25e-421d-8f16-1be2947cbf27)

## Requested solution
Please could you update the new date logic to continue to support the old ([documented](https://github.com/0w0miki/logseq-plugin-query-chart#advanced-query-%E9%AB%98%E7%BA%A7%E6%9F%A5%E8%AF%A2)) format and/or change the documentation to explain the new format

Thanks! ❤️

**Comment by 0w0miki** [comment]
I just follow the new built-in advanced query inputs. According to the document, the `:7d-before` is deprecated.
https://docs.logseq.com/#/page/advanced%20queries

I just made a test. Such kind of input still works in logseq, so I will add them back.

**Comment by mrdavidlaing** [comment]
Thanks for the extra context.

> Such kind of input still works in logseq, so I will add them back.

Alternatively, perhaps you could just change [the logseq-plugin-query-chart examples](https://github.com/0w0miki/logseq-plugin-query-chart#example-%E7%A4%BA%E4%BE%8B) and make the error message point out that `–before` has been duplicated

**Comment by mrdavidlaing** [comment]
Addressed by fd47ffd009f07f2f591fccdbc7aba548a609d6f1 and 658688a94997f234ae09de089e0dc66e613e863e
